### ISSUE TITLE
Is surprise really required?

### ISSUE THREAD

**Issue by bmcfee** [statisticianinstilettos/recmetrics#2]
First of all: this package looks great!  It's exactly what I need for some small projects, so thanks for putting it out there!

I'm looking at the setup.py, and it lists `surprise` as a requirement.  I don't see it imported anywhere in the package though, so I'm wondering if it can be removed?  I get that it's useful for the example notebook, but that wouldn't be included in the pip install anyway.  (I might suggest making `surprise` an `extras_require` if you want to keep it in there for demo purposes.)

If you're open to some packaging changes along these lines, I'd be happy to send a PR your way.

**Comment by statisticianinstilettos** [comment]
Hello. Thanks for bringing this to my attention. I agree, we should remove surprise since it is not required for pip install and only for demo. Feel free to make a PR. I appreciate the contribution.

**Comment by gregwchase** [comment]
Fixed in #26
