### ISSUE TITLE
ImportError: cannot import name 'signature'

### ISSUE THREAD

**Issue by hanshika0292** [statisticianinstilettos/recmetrics#23]
Getting following error when importing recmetrics.

<img width="1007" alt="Screenshot 2020-03-24 at 7 05 23 PM" src="https://user-images.githubusercontent.com/20727242/77431412-ad050a00-6e02-11ea-816d-2486f7187dae.png">

**Comment by caramelWaffle** [comment]
Same problem.

**Comment by yehjames** [comment]
same problem, any solution?

**Comment by Declow** [comment]
If you installed the library using `pip install recmetrics` then thats the problem.
The current version in pipy is outdated quite a bit. You might want to try and install using git.
`pip install -e git+https://github.com/statisticianinstilettos/recmetrics.git@master##egg=recmetrics`

**Comment by Prokledge** [comment]
When I run this: pip install -e git+https://github.com/statisticianinstilettos/recmetrics.git@master#egg=recmetrics.

I get the error below after successfully running the recommended pip ..... code .
ModuleNotFoundError: No module named 'recmetrics' when i run  'import recmetrics'

**Comment by Declow** [comment]
Did you remember to use the correct python version with the pip command?
Example om my pc pip3 is associated with python3 and pip is associated with python2.
So if I had to run the command I would have to change the command to
`pip3 install -e git+https://github.com/statisticianinstilettos/recmetrics.git@master#egg=recmetrics`

**Comment by Prokledge** [comment]
Still not working. I am even using google colab platform.

**Comment by Declow** [comment]
When using something like colab you need to remember to add "!" infront of the command.
Next it might be required that you restart the runtime.
I just did a test and it worked after a restart of the runtime.

**Comment by Coderanker3** [comment]
@Declow and how did you import it? 
Usually I do:
```
    !pip install x
    import x as x
```

**Comment by gregwchase** [comment]
Fixed in #26
