### ISSUE TITLE
Coverage over 100%

### ISSUE THREAD

**Issue by vascosmota** [statisticianinstilettos/recmetrics#40]
In the example bellow, the coverage measured exceeds 100%, which does not make sense.

This happens when items that are not listed on the catalog are recommended.

```
> from rcmetrics import prediction_coverage
> prediction_coverage([['x', 'y'], ['w', 'z']], catalog=['w', 'x', 'y'])
133.33
```

**Comment by vascosmota** [comment]
A solution could be allowing to set a behaviour when items not present on the catalog are seen. Either ignore them (and do not count them for the coverage measure) or throw an exception when these items are present.

**Comment by nikosT** [comment]
Why the code uses random.choices for? Should it just count existing input elements?
