### ISSUE TITLE
Implement MAP@k

### ISSUE THREAD

**Issue by j-adamczyk** [statisticianinstilettos/recmetrics#49]
MAP@k implementation linked in the documentation (https://github.com/benhamner/Metrics) has not been updated for 7 years and has bugs in MAP@k implementation (e.g. https://github.com/benhamner/Metrics/issues/51, https://github.com/benhamner/Metrics/issues/57). It would be really useful to have MAP@k implementation in `recmetrics`. Would it be possible to implement it? It would be almost identical to the existing `mark()` function.

**Comment by j-adamczyk** [comment]
Also, is MAR@k correct? It is almost exactly the MAP@k from `ml_metrics`, but with one bug fixed in the last line.

**Comment by Alex-Bujorianu** [comment]
I have this issue too. How can something so basic not be implemented in a library named recmetrics?

**Comment by statisticianinstilettos** [comment]
Hey everyone! Thanks for the feedback. I'd love to implement MAP@k in recmetrics, but I dont have the bandwidth today (I work for a startup :-) ) If anyone from the community is interested in contributing, I can review PRs and get it merged.

**Comment by statisticianinstilettos** [comment]
Thanks dream team. Love the community contributions to this one. :-)

**Comment by maayanorner** [comment]
Just a small question -

This merge made sense https://github.com/statisticianinstilettos/recmetrics/commit/e4e19050dd6db699cd375d2df10d446102d4b500
However, it seems like the master has another version, similar to the one here (https://github.com/benhamner/Metrics/issues/57).
From what I can see using git blame, it seems to me that the first implementation which is easy to understand was replaced here: https://github.com/statisticianinstilettos/recmetrics/pull/50/files

I am not sure I understand why the second one is better, I think the first one is easier to read. For what it's worth, I get the same results for both.

Sorry if it wastes your time :)
