### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MartinThoma** [statisticianinstilettos/recmetrics#5]
This is missing a license.  You can use https://tldrlegal.com/ for an overview. The top-3 are MIT, BSD and GPL (see [my analysis](https://martin-thoma.com/analyzing-pypi-metadata/)).

The simplest way to add it is in the setup.py as `license='MIT'` or similar.

**Comment by statisticianinstilettos** [comment]
Added MIT license to the repo. Thanks for the thorough analysis.

**Comment by MartinThoma** [comment]
I think there is a `'` missing: https://github.com/statisticianinstilettos/recmetrics/blob/master/setup.py#L25 ... but I wonder why the syntax highlighting doesn't show it. It might be just be being tired^^
